[2023-02-27T23:48:46.472+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:48:43.785624+00:00 [queued]>
[2023-02-27T23:48:46.479+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:48:43.785624+00:00 [queued]>
[2023-02-27T23:48:46.479+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T23:48:46.479+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-27T23:48:46.479+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T23:48:46.490+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2023-02-27 23:48:43.785624+00:00
[2023-02-27T23:48:46.495+0000] {standard_task_runner.py:55} INFO - Started process 3307 to run task
[2023-02-27T23:48:46.497+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'manual__2023-02-27T23:48:43.785624+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpwme3gihp']
[2023-02-27T23:48:46.497+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask delete_data_from_table
[2023-02-27T23:48:46.540+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:48:43.785624+00:00 [running]> on host 971ca163b440
[2023-02-27T23:48:46.597+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=temi109
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T23:48:43.785624+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T23:48:43.785624+00:00
[2023-02-27T23:48:46.597+0000] {sql.py:254} INFO - Executing: 
            delete from dag_runs where dt = '2023-02-27' and dag_id = 'dag_with_postgres_operator_v03';
        
[2023-02-27T23:48:46.604+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-27T23:48:46.775+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-27T23:48:46.783+0000] {sql.py:375} INFO - Running statement: 
            delete from dag_runs where dt = '2023-02-27' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2023-02-27T23:48:46.786+0000] {sql.py:384} INFO - Rows affected: 0
[2023-02-27T23:48:46.795+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20230227T234843, start_date=20230227T234846, end_date=20230227T234846
[2023-02-27T23:48:46.829+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-27T23:48:46.849+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
