[2023-02-28T20:25:30.200+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:25:29.423019+00:00 [queued]>
[2023-02-28T20:25:30.206+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:25:29.423019+00:00 [queued]>
[2023-02-28T20:25:30.206+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:25:30.207+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-28T20:25:30.207+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:25:30.217+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-02-28 20:25:29.423019+00:00
[2023-02-28T20:25:30.221+0000] {standard_task_runner.py:55} INFO - Started process 2600 to run task
[2023-02-28T20:25:30.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 's3_upload_test', 'postgres_to_s3', 'manual__2023-02-28T20:25:29.423019+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_dag.py', '--cfg-path', '/tmp/tmpeigdicp5']
[2023-02-28T20:25:30.223+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask postgres_to_s3
[2023-02-28T20:25:30.271+0000] {task_command.py:388} INFO - Running <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:25:29.423019+00:00 [running]> on host 2341ffaf5508
[2023-02-28T20:25:30.336+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tem109
AIRFLOW_CTX_DAG_ID=s3_upload_test
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T20:25:29.423019+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T20:25:29.423019+00:00
[2023-02-28T20:25:30.343+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-28T20:25:30.360+0000] {s3_upload_dag.py:31} INFO - Saved orders data in text file: dags/get_orders_20230228.txt
[2023-02-28T20:25:30.367+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2023-02-28T20:25:30.367+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-02-28T20:25:31.269+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-02-28T20:25:31.277+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=s3_upload_test, task_id=postgres_to_s3, execution_date=20230228T202529, start_date=20230228T202530, end_date=20230228T202531
[2023-02-28T20:25:31.318+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-28T20:25:31.331+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
