[2023-02-27T23:45:19.649+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:45:17.473925+00:00 [queued]>
[2023-02-27T23:45:19.657+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:45:17.473925+00:00 [queued]>
[2023-02-27T23:45:19.658+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T23:45:19.658+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-27T23:45:19.658+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T23:45:19.668+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2023-02-27 23:45:17.473925+00:00
[2023-02-27T23:45:19.673+0000] {standard_task_runner.py:55} INFO - Started process 2950 to run task
[2023-02-27T23:45:19.675+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'manual__2023-02-27T23:45:17.473925+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpffeciph6']
[2023-02-27T23:45:19.675+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask delete_data_from_table
[2023-02-27T23:45:19.718+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table manual__2023-02-27T23:45:17.473925+00:00 [running]> on host 971ca163b440
[2023-02-27T23:45:19.771+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=temi109
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T23:45:17.473925+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T23:45:17.473925+00:00
[2023-02-27T23:45:19.771+0000] {sql.py:254} INFO - Executing: 
            delete from dag_runs where dt = '2023-02-27' and dag_id = 'dag_with_postgres_operator_v03';
        
[2023-02-27T23:45:19.777+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-27T23:45:19.944+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-27T23:45:19.952+0000] {sql.py:375} INFO - Running statement: 
            delete from dag_runs where dt = '2023-02-27' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2023-02-27T23:45:19.955+0000] {sql.py:384} INFO - Rows affected: 1
[2023-02-27T23:45:19.964+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20230227T234517, start_date=20230227T234519, end_date=20230227T234519
[2023-02-27T23:45:20.007+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-27T23:45:20.024+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
